### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Suksal** [awuu/FlexibleTableView#2]
the demo is alright ，but i try to run it ,and i found a problem in it , the function is that    func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath)   and      func tableView(tableView: UITableView, didSelectSubRowAtIndexPath indexPath: NSIndexPath),,,  i think  when i choose didSelectSubRowAtIndexPath, the indexPath should be FlexibleIndexPath,

**Comment by haowenwu** [comment]
true. I just fix this issue in a4aaf31b503dcf2935b0aabb4a38722d1dcb6fb5 .
