### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [awuu/FlexibleTableView#3]
How can i add values from TextField to the araay ? 
and what is data type of "contents" in example ? 

may you show me an example how can i use it with textfield ?

**Comment by haowenwu** [comment]
"contents" in example is [Array<Array<String>>], which used in "cellForRowAtIndexPath" to define the data of the tableView and you can change it to anything you want.

You can change it to var, and assign it through a button or something, then call the reloadData() that's it.
